### ISSUE TITLE
Trim path C:\xampp\htdocs\wp-content\uploads\static-html-output\ for ZIP Deployment via XAMPP

### ISSUE THREAD

**Issue by thegulshankumar** [WP2Static/static-html-output#114]
Technical Details | Path
-- | --
ABSPATH | C:\xampp\htdocs/
WP_HOME | Undefined
WP_SITEURL | Undefined
WP_CONTENT_DIR | C:\xampp\htdocs/wp-content
WP_PLUGIN_DIR | C:\xampp\htdocs/wp-content/plugins

**Visual Representation**
<img src="https://i.imgur.com/KaSrVt7.gif">

**Steps**

0. Choosing ZIP Deployment, Setup Deployment URL and then start crawling, exporting.

_Main steps_
1. Download & Extract **static-html-output.zip**

![image](https://user-images.githubusercontent.com/23408127/85898982-efcbe900-b81a-11ea-95d1-eec31f90996d.png)

2. Archive all files inside `C:\Users\Gulshan Kumar\Downloads\C_\xampp\htdocs\wp-content\uploads\static-html-output`

From
![image](https://user-images.githubusercontent.com/23408127/85899400-9ca66600-b81b-11ea-97b5-3f14109a8a15.png)

To

![image](https://user-images.githubusercontent.com/23408127/85899856-63222a80-b81c-11ea-928a-cd73524aae7a.png)

Note: Here `C_\xampp\htdocs\wp-content\uploads\static-html-output` deep directories is uneccessary. So I had to build new zip here. 

Guess, C: was replaced with C_ via 7zip app after extraction as Win dont allow : symbol for any file/folder.
![image](https://user-images.githubusercontent.com/23408127/85900369-5b16ba80-b81d-11ea-8ffe-26e96a97f38a.png)

4. Finally, Upload `static-html-output.zip` to Deployment server manually.

I was able to successfully deploy. Ref: https://omgstatic.netlify.app 😊

**Feedback**

- It would be perfect after cutting this path `C:\xampp\htdocs\wp-content\uploads\static-html-output\`

Other
- All looks good to me, except missing /uncategorized/ category URL.

Thanks

**Comment by thegulshankumar** [comment]
Guess, This issue is resolved with [this build](https://github.com/WP2Static/static-html-output-plugin/files/4943854/gulshanwinziptest.zip) the latest and should be marked as closed.

**Comment by leonstafford** [comment]
Thanks @thegulshankumar - I'll close it off when I merge that code in / publish new release. Most people still don't have that build, so I'll keep it open - also as reminder for me :)
